[2020-03-03T10:07:52.462317+00:00] php.DEBUG: Warning: filemtime(): stat failed for /app/config/routes/dev/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/project/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/var/www/project/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2020-03-03T10:07:52.502579+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-03T10:07:52.702978+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"425757"},"request_uri":"http://localhost:8010/_wdt/425757","method":"GET"} []
[2020-03-03T10:07:52.940761+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8010/")" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8010/\") at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2020-03-03T10:10:31.877547+00:00] php.DEBUG: Warning: filemtime(): stat failed for /var/www/project/config/routes/dev/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/app/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/app/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2020-03-03T14:33:32.667292+00:00] php.DEBUG: Warning: filemtime(): stat failed for /app/config/routes/dev/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/project/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/var/www/project/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2020-03-03T14:33:32.748422+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8010/")" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8010/\") at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2020-03-03T14:33:32.965505+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-03T14:33:33.284221+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"05b142"},"request_uri":"http://localhost:8010/_wdt/05b142","method":"GET"} []
[2020-03-03T14:33:36.008660+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-03T14:33:36.299442+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"eca011"},"request_uri":"http://localhost:8010/_wdt/eca011","method":"GET"} []
[2020-03-03T14:33:36.819934+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-03T14:33:37.096767+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0b67c9"},"request_uri":"http://localhost:8010/_wdt/0b67c9","method":"GET"} []
[2020-03-03T14:33:37.787568+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/project/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/project/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-03T14:33:38.029540+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"90d2bd"},"request_uri":"http://localhost:8010/_wdt/90d2bd","method":"GET"} []
[2020-03-03T15:35:18.959857+01:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client"} []
[2020-03-03T15:35:18.960916+01:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-03T15:36:57.419101+01:00] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client"} []
[2020-03-03T15:36:57.420155+01:00] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2020-03-03T14:39:13.169671+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:39:13.171803+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-03T14:42:24.991852+00:00] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:42:24.993921+00:00] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2020-03-03T14:45:03.992095+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:45:03.994270+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-03T14:45:10.057298+00:00] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:45:10.059429+00:00] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2020-03-03T15:45:20.363438+01:00] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2054): SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] at /home/charles/Bureau/Symfony/partiels_ipssi/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client"} []
[2020-03-03T15:45:20.364506+01:00] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2020-03-03T14:47:57.371405+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:47:57.373521+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-03T14:56:00.254214+00:00] php.DEBUG: Warning: filemtime(): stat failed for /var/www/project/config/routes/dev/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/app/vendor/symfony/config/Resource/FileResource.php","line":65,"trace":[{"file":"/app/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2020-03-03T14:56:13.813478+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T14:56:13.815607+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-03T15:11:48.879164+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-03T15:11:48.881499+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
